### PR TITLE
feat: export StepperIcon component

### PR DESCRIPTION
**Pull request by lukicenturi**
Closes #(issue_number)

### CODE REVIEW

**Comment by kelsos** [comment]
@lukicenturi what are you going to do with the exported stepper icon?

**Comment by lukicenturi** [comment]
> @lukicenturi what are you going to do with the exported stepper icon?

I need to use custom-icon slot, so I can add the progress bar there 
image

**Comment by kelsos** [comment]
Can't we integrate what are you trying to do in the stepper itself instead of exporting the StepperIcon and implementing externally?

**Comment by lukicenturi** [comment]
> Can't we integrate what are you trying to do in the stepper itself instead of exporting the StepperIcon and implementing externally?

okay I think I'll just add `loading` to the step data.

**Comment by kelsos** [comment]
Great, don't forget to also create PRs with these changes, and the RuiButton `list` changes to the main library. I tried to do a rebase of the vue 3 branch and we are also missing that :)

**Review by kelsos — APPROVED** [review]
lgtm

**Pull request merged**
